### ISSUE TITLE
Handle deleting single timesheet entries before submit.

### ISSUE THREAD

**Issue by BeckyPollard** [badgateway/tt-api#35]
Create a new `HTTP` method, `DELETE`, on the `Entry` item controller.

Need to let users delete content they created.
- Delete timesheet entries.

**Comment by evert** [comment]
With the exception of being able to delete time-entries (before they are frozen?) i think most of these could probably be done post-mvp? 

It's not uncommon for MVP-style applications to require an email to support for more drastic delete operations. They are a little tricky

**Comment by BeckyPollard** [comment]
i thought just clicking a button to delete/remove a submitted time entry would be basic, but if it's something that is best addressed in a later milestone that's totally cool
